### PR TITLE
Add tests and CI integrations

### LINKED ISSUE #16: Add Travis and Appveyor tests
@noerw Happy to contribute some automated tests for https://github.com/noerw/opensensmapR/milestone/2

### PR DESCRIPTION
**Pull request by nuest**
_PR is not ready for merge_, but feedback is welcome. Once completed this closes #16 (if Travis and Appveyor are activated for the main repo).

## CI

Travis and Appveyor tests run for my fork (but not all tests work yet), see

- https://travis-ci.org/nuest/opensensmapR/jobs/328824676
- https://ci.appveyor.com/project/nuest/opensensmapr/build/1.0.2

## Tests

image

@noerw Can you take a look why a coercion to sf looses the attribute names? See https://github.com/nuest/opensensmapR/blob/master/tests/testthat/test_box.R#L13

## Open tasks

- [x] add more tests for `osem_measurements` @nuest
- [x] fix test for coercion to sf objects (looses attribute names) @noerw 
- [x] bump version

### CODE REVIEW

**Comment by nuest** [comment]
@noerw Also added myself to the list of package contributors, hope you agree that is justified by the contributions.

**Comment by nuest** [comment]
I'm done from my side... tests work on Travis and Appveyor, you only must activate this repo on both platforms. Not sure how the integration with codecov works best... I'd like to look into that after a merge. It might simply be better to call `covr::package_..` to get the coverage within the test logs, but the visual reports are nice:

https://codecov.io/gh/nuest/opensensmapR/tree/d82b538b7a7a0a1b593657a073eaef8f888ca6b0/R

**Comment by noerw** [comment]
Wow, thank you for all this work!

Minor remarks:
- I have read that it's a best practice to run `skip_on_cran()` [[1]](https://www.rdocumentation.org/packages/testthat/versions/2.0.0/topics/skip) for all tests that make a call to the API:  [[2 (search for `skip_on_cran`)]](https://github.com/ropensci/onboarding/issues/24#issuecomment-176629959). added this in `7e7b9bc`
- You use a different code style. I'm not very opinonated about this, but style should be consistent. We don't have to fix this now, but I will add a `lintR` config soon. (#20)
- The failing test was due to a bug in the `[.sensebox` implementation. Overriding data.frame functions is an antipattern anyway, I'm considering to use tibbles as a base instead. (#19)

I will set up the CI services in the next days, and merge once that's done.

**Comment by nuest** [comment]
Thanks for merging and the feedback.

About `skip_on_cran`: sure, we can do that, #21
About the code style: Yes, but mine's better ;-). Just kidding, happy to update this once you've configured a linter.
About the `data.frame` overrides: I don't think it's such a bad practice, is it? I think `sf` does it too. Maybe it's simply about not putting the `sensebox` class first?

**Comment by noerw** [comment]
When fixing failing tests I noticed that appveyor does not build vignettes (https://github.com/krlmlr/r-appveyor/issues/83), and seems to [incorrectly run tests](https://ci.appveyor.com/project/noerw/opensensmapr/build/1.0.3):

```
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'testthat.R'        <-- should load all the other tests & eventually fail?
 OK
* DONE
```

@nuest Do you know how to fix the latter issue?

**Comment by nuest** [comment]
IMHO the vignettes not being build is not an issue. Appveyor is there to make sure things run on Windows, and the tests take care of that.

Re. the tests: The tests are run and complete successfully, so the package log just has an `OK`. That's expected. For details you must take a look at the [build artifacts](https://ci.appveyor.com/project/noerw/opensensmapr/build/1.0.3/artifacts), file `testthat.Rout`:

```
> library("testthat")
> library("opensensmapr")
> library("sf")
Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
> 
> test_check("opensensmapr")
== testthat results  ===========================================================
OK: 9 SKIPPED: 26 FAILED: 0
> 
> proc.time()
   user  system elapsed 
   4.76    0.21    6.96 
```

Only 9 tests are OK, the rest is skipped, which seems to me like the API is not available during the tests... OR the `skip_on_cran()` takes effect, because [in an older configuration](https://ci.appveyor.com/project/nuest/opensensmapr/build/1.0.6/artifacts) the result was `OK: 42 SKIPPED: 1` (also seems like the overall number of tests decreased since then...).

**Pull request merged**
